using UnityEngine;
using UnityEditor;

public class CreateWordDataAssets {
    [MenuItem("WordData/Create Assets")]
    public static void CreateAssets() {
        WordContainer asset_0 = ScriptableObject.CreateInstance<WordContainer>();
        asset_0.englishWord = "person";
        asset_0.spanishWord = "persona";
        asset_0.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/persona.mp3");
        asset_0.definition = "An individual; usually a human being.";
        AssetDatabase.CreateAsset(asset_0, "Assets/Data/WordData/word_0.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_1 = ScriptableObject.CreateInstance<WordContainer>();
        asset_1.englishWord = "bicycle";
        asset_1.spanishWord = "bicicleta";
        asset_1.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/bicicleta.mp3");
        asset_1.definition = "A vehicle that has two wheels, one behind the other, a steering handle, and a saddle seat or seats and is usually propelled by the action of a rider’s feet upon pedals.";
        AssetDatabase.CreateAsset(asset_1, "Assets/Data/WordData/word_1.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_2 = ScriptableObject.CreateInstance<WordContainer>();
        asset_2.englishWord = "car";
        asset_2.spanishWord = "auto";
        asset_2.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/auto.mp3");
        asset_2.definition = "A wheeled vehicle that moves independently, with at least three wheels, powered mechanically, steered by a driver and mostly for personal transportation.";
        AssetDatabase.CreateAsset(asset_2, "Assets/Data/WordData/word_2.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_3 = ScriptableObject.CreateInstance<WordContainer>();
        asset_3.englishWord = "motorcycle";
        asset_3.spanishWord = "motocicleta";
        asset_3.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/motocicleta.mp3");
        asset_3.definition = "An open-seated motor vehicle with handlebars instead of a steering wheel, and having two (or sometimes three) wheels.";
        AssetDatabase.CreateAsset(asset_3, "Assets/Data/WordData/word_3.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_4 = ScriptableObject.CreateInstance<WordContainer>();
        asset_4.englishWord = "airplane";
        asset_4.spanishWord = "avión";
        asset_4.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/avión.mp3");
        asset_4.definition = "A powered heavier-than-air aircraft with fixed wings.";
        AssetDatabase.CreateAsset(asset_4, "Assets/Data/WordData/word_4.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_5 = ScriptableObject.CreateInstance<WordContainer>();
        asset_5.englishWord = "bus";
        asset_5.spanishWord = "autobús";
        asset_5.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/autobús.mp3");
        asset_5.definition = "A motor vehicle for transporting large numbers of people along roads.";
        AssetDatabase.CreateAsset(asset_5, "Assets/Data/WordData/word_5.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_6 = ScriptableObject.CreateInstance<WordContainer>();
        asset_6.englishWord = "train";
        asset_6.spanishWord = "tren";
        asset_6.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/tren.mp3");
        asset_6.definition = "Elongated portion.";
        AssetDatabase.CreateAsset(asset_6, "Assets/Data/WordData/word_6.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_7 = ScriptableObject.CreateInstance<WordContainer>();
        asset_7.englishWord = "truck";
        asset_7.spanishWord = "camión";
        asset_7.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/camión.mp3");
        asset_7.definition = "A small wheel or roller, specifically the wheel of a gun carriage.";
        AssetDatabase.CreateAsset(asset_7, "Assets/Data/WordData/word_7.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_8 = ScriptableObject.CreateInstance<WordContainer>();
        asset_8.englishWord = "boat";
        asset_8.spanishWord = "bote";
        asset_8.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/bote.mp3");
        asset_8.definition = "A craft used for transportation of goods, fishing, racing, recreational cruising, or military use on or in the water, propelled by oars or outboard motor or inboard motor or by wind.";
        AssetDatabase.CreateAsset(asset_8, "Assets/Data/WordData/word_8.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_9 = ScriptableObject.CreateInstance<WordContainer>();
        asset_9.englishWord = "traffic light";
        asset_9.spanishWord = "semáforo";
        asset_9.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/semáforo.mp3");
        asset_9.definition = "A signalling device positioned at a road intersection or pedestrian crossing to indicate when it may be safe to drive, ride or walk, using a universal colour code.";
        AssetDatabase.CreateAsset(asset_9, "Assets/Data/WordData/word_9.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_10 = ScriptableObject.CreateInstance<WordContainer>();
        asset_10.englishWord = "fire hydrant";
        asset_10.spanishWord = "boca de incendio";
        asset_10.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/boca de incendio.mp3");
        asset_10.definition = "A device used by firefighters to obtain water from the main supply, consisting of a barrel, connections for hose and a valve assembly.";
        AssetDatabase.CreateAsset(asset_10, "Assets/Data/WordData/word_10.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_11 = ScriptableObject.CreateInstance<WordContainer>();
        asset_11.englishWord = "stop sign";
        asset_11.spanishWord = "señal de stop";
        asset_11.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/señal de stop.mp3");
        asset_11.definition = "No definition found";
        AssetDatabase.CreateAsset(asset_11, "Assets/Data/WordData/word_11.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_12 = ScriptableObject.CreateInstance<WordContainer>();
        asset_12.englishWord = "parking meter";
        asset_12.spanishWord = "parquímetro";
        asset_12.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/parquímetro.mp3");
        asset_12.definition = "A device, located by a parking space, that collects payment in exchange for the right to park a vehicle for a specified time.";
        AssetDatabase.CreateAsset(asset_12, "Assets/Data/WordData/word_12.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_13 = ScriptableObject.CreateInstance<WordContainer>();
        asset_13.englishWord = "bench";
        asset_13.spanishWord = "banco";
        asset_13.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/banco.mp3");
        asset_13.definition = "A long seat with or without a back, found for example in parks and schools.";
        AssetDatabase.CreateAsset(asset_13, "Assets/Data/WordData/word_13.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_14 = ScriptableObject.CreateInstance<WordContainer>();
        asset_14.englishWord = "bird";
        asset_14.spanishWord = "pájaro";
        asset_14.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/pájaro.mp3");
        asset_14.definition = "A member of the class of animals Aves in the phylum Chordata, characterized by being warm-blooded, having feathers and wings usually capable of flight, and laying eggs.";
        AssetDatabase.CreateAsset(asset_14, "Assets/Data/WordData/word_14.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_15 = ScriptableObject.CreateInstance<WordContainer>();
        asset_15.englishWord = "cat";
        asset_15.spanishWord = "gato";
        asset_15.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/gato.mp3");
        asset_15.definition = "An animal of the family Felidae:";
        AssetDatabase.CreateAsset(asset_15, "Assets/Data/WordData/word_15.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_16 = ScriptableObject.CreateInstance<WordContainer>();
        asset_16.englishWord = "dog";
        asset_16.spanishWord = "perro";
        asset_16.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/perro.mp3");
        asset_16.definition = "A mammal, Canis familiaris or Canis lupus familiaris, that has been domesticated for thousands of years, of highly variable appearance due to human breeding.";
        AssetDatabase.CreateAsset(asset_16, "Assets/Data/WordData/word_16.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_17 = ScriptableObject.CreateInstance<WordContainer>();
        asset_17.englishWord = "horse";
        asset_17.spanishWord = "caballo";
        asset_17.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/caballo.mp3");
        asset_17.definition = "Any of several animals related to Equus ferus caballus.";
        AssetDatabase.CreateAsset(asset_17, "Assets/Data/WordData/word_17.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_18 = ScriptableObject.CreateInstance<WordContainer>();
        asset_18.englishWord = "sheep";
        asset_18.spanishWord = "oveja";
        asset_18.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/oveja.mp3");
        asset_18.definition = "A woolly ruminant of the genus Ovis.";
        AssetDatabase.CreateAsset(asset_18, "Assets/Data/WordData/word_18.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_19 = ScriptableObject.CreateInstance<WordContainer>();
        asset_19.englishWord = "cow";
        asset_19.spanishWord = "vaca";
        asset_19.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/vaca.mp3");
        asset_19.definition = "(properly) An adult female of the species Bos taurus, especially one that has calved.";
        AssetDatabase.CreateAsset(asset_19, "Assets/Data/WordData/word_19.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_20 = ScriptableObject.CreateInstance<WordContainer>();
        asset_20.englishWord = "elephant";
        asset_20.spanishWord = "elefante";
        asset_20.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/elefante.mp3");
        asset_20.definition = "A mammal of the order Proboscidea, having a trunk, and two large ivory tusks jutting from the upper jaw.";
        AssetDatabase.CreateAsset(asset_20, "Assets/Data/WordData/word_20.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_21 = ScriptableObject.CreateInstance<WordContainer>();
        asset_21.englishWord = "bear";
        asset_21.spanishWord = "oso";
        asset_21.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/oso.mp3");
        asset_21.definition = "A large omnivorous mammal, related to the dog and raccoon, having shaggy hair, a very small tail, and flat feet; a member of family Ursidae.";
        AssetDatabase.CreateAsset(asset_21, "Assets/Data/WordData/word_21.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_22 = ScriptableObject.CreateInstance<WordContainer>();
        asset_22.englishWord = "zebra";
        asset_22.spanishWord = "cebra";
        asset_22.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/cebra.mp3");
        asset_22.definition = "Any of three species of genus Equus: E. grevyi, E. quagga, or E. zebra, all with black and white stripes and native to Africa.";
        AssetDatabase.CreateAsset(asset_22, "Assets/Data/WordData/word_22.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_23 = ScriptableObject.CreateInstance<WordContainer>();
        asset_23.englishWord = "giraffe";
        asset_23.spanishWord = "jirafa";
        asset_23.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/jirafa.mp3");
        asset_23.definition = "A ruminant, of the genus Giraffa, of the African savannah with long legs and highly elongated neck, which make it the tallest living animal; yellow fur patterned with dark spots, often in the form of a network; and two or more short, skin-covered horns, so-called; strictly speaking the horn-like projections are ossicones.";
        AssetDatabase.CreateAsset(asset_23, "Assets/Data/WordData/word_23.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_24 = ScriptableObject.CreateInstance<WordContainer>();
        asset_24.englishWord = "backpack";
        asset_24.spanishWord = "mochila";
        asset_24.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/mochila.mp3");
        asset_24.definition = "A knapsack, sometimes mounted on a light frame, but always supported by straps, worn on a person’s back for the purpose of carrying things, especially when hiking, or on a student's back when carrying books.";
        AssetDatabase.CreateAsset(asset_24, "Assets/Data/WordData/word_24.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_25 = ScriptableObject.CreateInstance<WordContainer>();
        asset_25.englishWord = "umbrella";
        asset_25.spanishWord = "paraguas";
        asset_25.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/paraguas.mp3");
        asset_25.definition = "Cloth-covered frame used for protection against rain or sun.";
        AssetDatabase.CreateAsset(asset_25, "Assets/Data/WordData/word_25.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_26 = ScriptableObject.CreateInstance<WordContainer>();
        asset_26.englishWord = "handbag";
        asset_26.spanishWord = "bolso";
        asset_26.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/bolso.mp3");
        asset_26.definition = "(mainly Commonwealth) A small bag used by women (or sometimes by men) for carrying various small personal items.";
        AssetDatabase.CreateAsset(asset_26, "Assets/Data/WordData/word_26.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_27 = ScriptableObject.CreateInstance<WordContainer>();
        asset_27.englishWord = "tie";
        asset_27.spanishWord = "atar";
        asset_27.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/atar.mp3");
        asset_27.definition = "A knot; a fastening.";
        AssetDatabase.CreateAsset(asset_27, "Assets/Data/WordData/word_27.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_28 = ScriptableObject.CreateInstance<WordContainer>();
        asset_28.englishWord = "suitcase";
        asset_28.spanishWord = "maleta";
        asset_28.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/maleta.mp3");
        asset_28.definition = "A large (usually rectangular) piece of luggage used for carrying clothes, and sometimes suits, when travelling.";
        AssetDatabase.CreateAsset(asset_28, "Assets/Data/WordData/word_28.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_29 = ScriptableObject.CreateInstance<WordContainer>();
        asset_29.englishWord = "frisbee";
        asset_29.spanishWord = "disco volador";
        asset_29.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/disco volador.mp3");
        asset_29.definition = "A disk-shaped gliding toy.";
        AssetDatabase.CreateAsset(asset_29, "Assets/Data/WordData/word_29.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_30 = ScriptableObject.CreateInstance<WordContainer>();
        asset_30.englishWord = "skis";
        asset_30.spanishWord = "esquís";
        asset_30.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/esquís.mp3");
        asset_30.definition = "One of a pair of long flat runners designed for gliding over snow or water";
        AssetDatabase.CreateAsset(asset_30, "Assets/Data/WordData/word_30.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_31 = ScriptableObject.CreateInstance<WordContainer>();
        asset_31.englishWord = "snowboard";
        asset_31.spanishWord = "snowboard";
        asset_31.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/snowboard.mp3");
        asset_31.definition = "A board, somewhat like a broad ski, or a very long skateboard with no wheels, used in the sport of snowboarding.";
        AssetDatabase.CreateAsset(asset_31, "Assets/Data/WordData/word_31.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_32 = ScriptableObject.CreateInstance<WordContainer>();
        asset_32.englishWord = "sports ball";
        asset_32.spanishWord = "pelota deportiva";
        asset_32.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/pelota deportiva.mp3");
        asset_32.definition = "No definition found";
        AssetDatabase.CreateAsset(asset_32, "Assets/Data/WordData/word_32.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_33 = ScriptableObject.CreateInstance<WordContainer>();
        asset_33.englishWord = "kite";
        asset_33.spanishWord = "ver";
        asset_33.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/ver.mp3");
        asset_33.definition = "No definition found";
        AssetDatabase.CreateAsset(asset_33, "Assets/Data/WordData/word_33.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_34 = ScriptableObject.CreateInstance<WordContainer>();
        asset_34.englishWord = "baseball bat";
        asset_34.spanishWord = "bate de béisbol";
        asset_34.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/bate de béisbol.mp3");
        asset_34.definition = "No definition found";
        AssetDatabase.CreateAsset(asset_34, "Assets/Data/WordData/word_34.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_35 = ScriptableObject.CreateInstance<WordContainer>();
        asset_35.englishWord = "baseball glove";
        asset_35.spanishWord = "guante de béisbol";
        asset_35.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/guante de béisbol.mp3");
        asset_35.definition = "No definition found";
        AssetDatabase.CreateAsset(asset_35, "Assets/Data/WordData/word_35.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_36 = ScriptableObject.CreateInstance<WordContainer>();
        asset_36.englishWord = "skateboard";
        asset_36.spanishWord = "patineta";
        asset_36.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/patineta.mp3");
        asset_36.definition = "A narrow, wooden or plastic platform mounted on pairs of wheels, on which one stands and propels oneself by pushing along the ground with one foot.";
        AssetDatabase.CreateAsset(asset_36, "Assets/Data/WordData/word_36.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_37 = ScriptableObject.CreateInstance<WordContainer>();
        asset_37.englishWord = "surfboard";
        asset_37.spanishWord = "tabla de surf";
        asset_37.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/tabla de surf.mp3");
        asset_37.definition = "A shaped waterproof plank, usually made of wood or foam and reinforced plastic, used to surf on waves.";
        AssetDatabase.CreateAsset(asset_37, "Assets/Data/WordData/word_37.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_38 = ScriptableObject.CreateInstance<WordContainer>();
        asset_38.englishWord = "tennis racket";
        asset_38.spanishWord = "raqueta de tenis";
        asset_38.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/raqueta de tenis.mp3");
        asset_38.definition = "No definition found";
        AssetDatabase.CreateAsset(asset_38, "Assets/Data/WordData/word_38.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_39 = ScriptableObject.CreateInstance<WordContainer>();
        asset_39.englishWord = "bottle";
        asset_39.spanishWord = "botella";
        asset_39.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/botella.mp3");
        asset_39.definition = "A container, typically made of glass or plastic and having a tapered neck, used primarily for holding liquids.";
        AssetDatabase.CreateAsset(asset_39, "Assets/Data/WordData/word_39.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_40 = ScriptableObject.CreateInstance<WordContainer>();
        asset_40.englishWord = "wine glass";
        asset_40.spanishWord = "Copa de vino";
        asset_40.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/Copa de vino.mp3");
        asset_40.definition = "A glass vessel, normally with a stem, from which wine is drunk.";
        AssetDatabase.CreateAsset(asset_40, "Assets/Data/WordData/word_40.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_41 = ScriptableObject.CreateInstance<WordContainer>();
        asset_41.englishWord = "cup";
        asset_41.spanishWord = "taza";
        asset_41.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/taza.mp3");
        asset_41.definition = "A concave vessel for drinking from, usually made of opaque material (as opposed to a glass) and with a handle.";
        AssetDatabase.CreateAsset(asset_41, "Assets/Data/WordData/word_41.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_42 = ScriptableObject.CreateInstance<WordContainer>();
        asset_42.englishWord = "fork";
        asset_42.spanishWord = "tenedor";
        asset_42.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/tenedor.mp3");
        asset_42.definition = "A pronged tool having a long straight handle, used for digging, lifting, throwing etc.";
        AssetDatabase.CreateAsset(asset_42, "Assets/Data/WordData/word_42.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_43 = ScriptableObject.CreateInstance<WordContainer>();
        asset_43.englishWord = "knife";
        asset_43.spanishWord = "cuchillo";
        asset_43.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/cuchillo.mp3");
        asset_43.definition = "A utensil or a tool designed for cutting, consisting of a flat piece of hard material, usually steel or other metal (the blade), usually sharpened on one edge, attached to a handle. The blade may be pointed for piercing.";
        AssetDatabase.CreateAsset(asset_43, "Assets/Data/WordData/word_43.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_44 = ScriptableObject.CreateInstance<WordContainer>();
        asset_44.englishWord = "spoon";
        asset_44.spanishWord = "cuchara";
        asset_44.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/cuchara.mp3");
        asset_44.definition = "An implement for eating or serving; a scooped utensil whose long handle is straight, in contrast to a ladle.";
        AssetDatabase.CreateAsset(asset_44, "Assets/Data/WordData/word_44.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_45 = ScriptableObject.CreateInstance<WordContainer>();
        asset_45.englishWord = "bowl";
        asset_45.spanishWord = "bol";
        asset_45.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/bol.mp3");
        asset_45.definition = "A roughly hemispherical container used to hold, mix or present food, such as salad, fruit or soup, or other items.";
        AssetDatabase.CreateAsset(asset_45, "Assets/Data/WordData/word_45.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_46 = ScriptableObject.CreateInstance<WordContainer>();
        asset_46.englishWord = "banana";
        asset_46.spanishWord = "banana";
        asset_46.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/banana.mp3");
        asset_46.definition = "An elongated curved tropical fruit that grows in bunches and has a creamy flesh and a smooth skin.";
        AssetDatabase.CreateAsset(asset_46, "Assets/Data/WordData/word_46.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_47 = ScriptableObject.CreateInstance<WordContainer>();
        asset_47.englishWord = "apple";
        asset_47.spanishWord = "manzana";
        asset_47.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/manzana.mp3");
        asset_47.definition = "A common, round fruit produced by the tree Malus domestica, cultivated in temperate climates.";
        AssetDatabase.CreateAsset(asset_47, "Assets/Data/WordData/word_47.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_48 = ScriptableObject.CreateInstance<WordContainer>();
        asset_48.englishWord = "sandwich";
        asset_48.spanishWord = "sándwich";
        asset_48.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/sándwich.mp3");
        asset_48.definition = "A dish or foodstuff where two or more slices of bread serve as the wrapper or container of some other food.";
        AssetDatabase.CreateAsset(asset_48, "Assets/Data/WordData/word_48.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_49 = ScriptableObject.CreateInstance<WordContainer>();
        asset_49.englishWord = "orange";
        asset_49.spanishWord = "naranja";
        asset_49.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/naranja.mp3");
        asset_49.definition = "An evergreen tree of the genus Citrus such as Citrus sinensis.";
        AssetDatabase.CreateAsset(asset_49, "Assets/Data/WordData/word_49.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_50 = ScriptableObject.CreateInstance<WordContainer>();
        asset_50.englishWord = "broccoli";
        asset_50.spanishWord = "brócoli";
        asset_50.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/brócoli.mp3");
        asset_50.definition = "A plant, Brassica oleracea var. italica, of the cabbage family, Brassicaceae; especially, the tree-shaped flower and stalk that are eaten as a vegetable.";
        AssetDatabase.CreateAsset(asset_50, "Assets/Data/WordData/word_50.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_51 = ScriptableObject.CreateInstance<WordContainer>();
        asset_51.englishWord = "carrot";
        asset_51.spanishWord = "zanahoria";
        asset_51.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/zanahoria.mp3");
        asset_51.definition = "A vegetable with a nutritious, juicy, sweet root that is often orange in colour, Daucus carota, especially the subspecies sativus in the family Apiaceae.";
        AssetDatabase.CreateAsset(asset_51, "Assets/Data/WordData/word_51.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_52 = ScriptableObject.CreateInstance<WordContainer>();
        asset_52.englishWord = "hot dog";
        asset_52.spanishWord = "Hot dog";
        asset_52.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/Hot dog.mp3");
        asset_52.definition = "A sandwich consisting of a frankfurter, or wiener, in a bread roll, usually served with ketchup, mustard, relish, etc.";
        AssetDatabase.CreateAsset(asset_52, "Assets/Data/WordData/word_52.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_53 = ScriptableObject.CreateInstance<WordContainer>();
        asset_53.englishWord = "pizza";
        asset_53.spanishWord = "pizza";
        asset_53.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/pizza.mp3");
        asset_53.definition = "A baked Italian dish of a thinly rolled bread dough crust typically topped before baking with tomato sauce, cheese and other ingredients such as meat, vegetables or fruit";
        AssetDatabase.CreateAsset(asset_53, "Assets/Data/WordData/word_53.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_54 = ScriptableObject.CreateInstance<WordContainer>();
        asset_54.englishWord = "donut";
        asset_54.spanishWord = "rosquilla";
        asset_54.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/rosquilla.mp3");
        asset_54.definition = "A deep-fried piece of dough or batter, commonly made in a toroidal or ellipsoidal shape, and mixed with various sweeteners and flavors, sometimes filled with jelly, custard or cream.";
        AssetDatabase.CreateAsset(asset_54, "Assets/Data/WordData/word_54.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_55 = ScriptableObject.CreateInstance<WordContainer>();
        asset_55.englishWord = "cake";
        asset_55.spanishWord = "pastel";
        asset_55.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/pastel.mp3");
        asset_55.definition = "A rich, sweet dessert food, typically made of flour, sugar and eggs and baked in an oven, and often covered in icing.";
        AssetDatabase.CreateAsset(asset_55, "Assets/Data/WordData/word_55.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_56 = ScriptableObject.CreateInstance<WordContainer>();
        asset_56.englishWord = "chair";
        asset_56.spanishWord = "silla";
        asset_56.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/silla.mp3");
        asset_56.definition = "An item of furniture used to sit on or in, comprising a seat, legs, back, and sometimes arm rests, for use by one person. Compare stool, couch, sofa, settee, loveseat and bench.";
        AssetDatabase.CreateAsset(asset_56, "Assets/Data/WordData/word_56.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_57 = ScriptableObject.CreateInstance<WordContainer>();
        asset_57.englishWord = "couch";
        asset_57.spanishWord = "sofá";
        asset_57.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/sofá.mp3");
        asset_57.definition = "Couch grass, a species of persistent grass, Elymus repens, usually considered a weed.";
        AssetDatabase.CreateAsset(asset_57, "Assets/Data/WordData/word_57.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_58 = ScriptableObject.CreateInstance<WordContainer>();
        asset_58.englishWord = "potted plant";
        asset_58.spanishWord = "planta en maceta";
        asset_58.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/planta en maceta.mp3");
        asset_58.definition = "No definition found";
        AssetDatabase.CreateAsset(asset_58, "Assets/Data/WordData/word_58.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_59 = ScriptableObject.CreateInstance<WordContainer>();
        asset_59.englishWord = "bed";
        asset_59.spanishWord = "cama";
        asset_59.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/cama.mp3");
        asset_59.definition = "A piece of furniture, usually flat and soft, on which to rest or sleep.";
        AssetDatabase.CreateAsset(asset_59, "Assets/Data/WordData/word_59.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_60 = ScriptableObject.CreateInstance<WordContainer>();
        asset_60.englishWord = "dining table";
        asset_60.spanishWord = "comedor";
        asset_60.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/comedor.mp3");
        asset_60.definition = "A table, usually in a dining room, on which meals are served.";
        AssetDatabase.CreateAsset(asset_60, "Assets/Data/WordData/word_60.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_61 = ScriptableObject.CreateInstance<WordContainer>();
        asset_61.englishWord = "toilet";
        asset_61.spanishWord = "baño";
        asset_61.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/baño.mp3");
        asset_61.definition = "A covering of linen, silk, or tapestry, spread over a dressing table in a chamber or dressing room.";
        AssetDatabase.CreateAsset(asset_61, "Assets/Data/WordData/word_61.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_62 = ScriptableObject.CreateInstance<WordContainer>();
        asset_62.englishWord = "TV";
        asset_62.spanishWord = "TELEVISOR";
        asset_62.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/TELEVISOR.mp3");
        asset_62.definition = "The assessed value of an asset from which the tax owing is computed.";
        AssetDatabase.CreateAsset(asset_62, "Assets/Data/WordData/word_62.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_63 = ScriptableObject.CreateInstance<WordContainer>();
        asset_63.englishWord = "laptop";
        asset_63.spanishWord = "computadora portátil";
        asset_63.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/computadora portátil.mp3");
        asset_63.definition = "A laptop computer.";
        AssetDatabase.CreateAsset(asset_63, "Assets/Data/WordData/word_63.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_64 = ScriptableObject.CreateInstance<WordContainer>();
        asset_64.englishWord = "mouse";
        asset_64.spanishWord = "ratón";
        asset_64.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/ratón.mp3");
        asset_64.definition = "Any small rodent of the genus Mus.";
        AssetDatabase.CreateAsset(asset_64, "Assets/Data/WordData/word_64.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_65 = ScriptableObject.CreateInstance<WordContainer>();
        asset_65.englishWord = "remote";
        asset_65.spanishWord = "remoto";
        asset_65.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/remoto.mp3");
        asset_65.definition = "An element of broadcast programming originating away from the station's or show's control room.";
        AssetDatabase.CreateAsset(asset_65, "Assets/Data/WordData/word_65.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_66 = ScriptableObject.CreateInstance<WordContainer>();
        asset_66.englishWord = "keyboard";
        asset_66.spanishWord = "teclado";
        asset_66.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/teclado.mp3");
        asset_66.definition = "(etc.) A set of keys used to operate a typewriter, computer etc.";
        AssetDatabase.CreateAsset(asset_66, "Assets/Data/WordData/word_66.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_67 = ScriptableObject.CreateInstance<WordContainer>();
        asset_67.englishWord = "cell phone";
        asset_67.spanishWord = "Teléfono móvil";
        asset_67.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/Teléfono móvil.mp3");
        asset_67.definition = "A portable, wireless telephone, which changes antenna connections seamlessly during travel from one radio reception cell to another without losing the party-to-party call connection.";
        AssetDatabase.CreateAsset(asset_67, "Assets/Data/WordData/word_67.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_68 = ScriptableObject.CreateInstance<WordContainer>();
        asset_68.englishWord = "microwave";
        asset_68.spanishWord = "microonda";
        asset_68.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/microonda.mp3");
        asset_68.definition = "An electromagnetic wave with wavelength between that of infrared light and radio waves.";
        AssetDatabase.CreateAsset(asset_68, "Assets/Data/WordData/word_68.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_69 = ScriptableObject.CreateInstance<WordContainer>();
        asset_69.englishWord = "oven";
        asset_69.spanishWord = "horno";
        asset_69.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/horno.mp3");
        asset_69.definition = "A chamber used for baking or heating.";
        AssetDatabase.CreateAsset(asset_69, "Assets/Data/WordData/word_69.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_70 = ScriptableObject.CreateInstance<WordContainer>();
        asset_70.englishWord = "toaster";
        asset_70.spanishWord = "tostadora";
        asset_70.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/tostadora.mp3");
        asset_70.definition = "One who toasts (cooks lightly by browning).";
        AssetDatabase.CreateAsset(asset_70, "Assets/Data/WordData/word_70.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_71 = ScriptableObject.CreateInstance<WordContainer>();
        asset_71.englishWord = "sink";
        asset_71.spanishWord = "hundir";
        asset_71.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/hundir.mp3");
        asset_71.definition = "A basin used for holding water for washing.";
        AssetDatabase.CreateAsset(asset_71, "Assets/Data/WordData/word_71.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_72 = ScriptableObject.CreateInstance<WordContainer>();
        asset_72.englishWord = "refrigerator";
        asset_72.spanishWord = "refrigerador";
        asset_72.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/refrigerador.mp3");
        asset_72.definition = "A household appliance used for keeping food fresh by refrigeration (short form fridge).";
        AssetDatabase.CreateAsset(asset_72, "Assets/Data/WordData/word_72.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_73 = ScriptableObject.CreateInstance<WordContainer>();
        asset_73.englishWord = "book";
        asset_73.spanishWord = "libro";
        asset_73.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/libro.mp3");
        asset_73.definition = "A collection of sheets of paper bound together to hinge at one edge, containing printed or written material, pictures, etc.";
        AssetDatabase.CreateAsset(asset_73, "Assets/Data/WordData/word_73.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_74 = ScriptableObject.CreateInstance<WordContainer>();
        asset_74.englishWord = "clock";
        asset_74.spanishWord = "reloj";
        asset_74.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/reloj.mp3");
        asset_74.definition = "An instrument used to measure or keep track of time; a non-portable timepiece.";
        AssetDatabase.CreateAsset(asset_74, "Assets/Data/WordData/word_74.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_75 = ScriptableObject.CreateInstance<WordContainer>();
        asset_75.englishWord = "vase";
        asset_75.spanishWord = "florero";
        asset_75.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/florero.mp3");
        asset_75.definition = "An upright open container used mainly for displaying fresh, dried, or artificial flowers.";
        AssetDatabase.CreateAsset(asset_75, "Assets/Data/WordData/word_75.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_76 = ScriptableObject.CreateInstance<WordContainer>();
        asset_76.englishWord = "scissors";
        asset_76.spanishWord = "tijeras";
        asset_76.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/tijeras.mp3");
        asset_76.definition = "One blade on a pair of scissors.";
        AssetDatabase.CreateAsset(asset_76, "Assets/Data/WordData/word_76.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_77 = ScriptableObject.CreateInstance<WordContainer>();
        asset_77.englishWord = "teddy bear";
        asset_77.spanishWord = "oso de peluche";
        asset_77.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/oso de peluche.mp3");
        asset_77.definition = "A plush toy in the shape of a bear.";
        AssetDatabase.CreateAsset(asset_77, "Assets/Data/WordData/word_77.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_78 = ScriptableObject.CreateInstance<WordContainer>();
        asset_78.englishWord = "hair drier";
        asset_78.spanishWord = "Secadora de pelo";
        asset_78.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/Secadora de pelo.mp3");
        asset_78.definition = "No definition found";
        AssetDatabase.CreateAsset(asset_78, "Assets/Data/WordData/word_78.asset");
        AssetDatabase.SaveAssets();
        WordContainer asset_79 = ScriptableObject.CreateInstance<WordContainer>();
        asset_79.englishWord = "toothbrush";
        asset_79.spanishWord = "cepillo de dientes";
        asset_79.pronounciationClip = AssetDatabase.LoadAssetAtPath<AudioClip>("Assets/Data/Audio/cepillo de dientes.mp3");
        asset_79.definition = "A brush, used with toothpaste, for cleaning the teeth.";
        AssetDatabase.CreateAsset(asset_79, "Assets/Data/WordData/word_79.asset");
        AssetDatabase.SaveAssets();
        EditorUtility.DisplayDialog("Asset Creation", "Word Data Assets Created", "OK");
    }
}
